AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Roles'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Service Account Roles Environment'
      Parameters:
      - AppName
      - OIDC
      - KubernetesNamespace
      - KubernetesServiceAccount

Parameters:
  AppName:
    Type: String
    Description: Enter the Application Name
    Default: jenkins-app
  OIDC:
    Type: String
    Description: Enter the OIDC Provider
    Default: oidc.eks.us-east-2.amazonaws.com/id/E43D7AC4307807243E7D231E16BD2CA5
  KubernetesNamespace:
    Type: String
    Description: Enter the Jenkins Namespace
    Default: jenkins
  KubernetesServiceAccount:
    Type: String
    Description: Enter the Jenkins Agent Service Account Name
    Default: jenkins-agent

Resources:
  EKSCloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-cloudformation-role"
      AssumeRolePolicyDocument: !Sub |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OIDC}"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "${OIDC}:sub": "system:serviceaccount:${KubernetesNamespace}:${KubernetesServiceAccount}"
                }
              }
            }
          ]
        }
      Path: !Sub /service-role/${AppName}/
      Policies:
        - PolicyName: !Sub "${AppName}-eks-cloudformation-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: [sts:AssumeRole]
              Resource: "arn:aws:iam::*:role/AWSCloudFormationStackSetExecutionRole"