apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-pipeline-pod
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
    fsGroup: 0
    runAsNonRoot: false
  containers:
  - name: custom-image
    image: docker.io/tpatrick1496/inbound-agent:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1024Mi