AWSTemplateFormatVersion: "2010-09-09"
Description: "Artifacts Bucket"

Parameters:
  S3BucketName:
    Type: String
    Default: artifacts-bucket

Resources:
################################################################################################
# S3 Bucket
################################################################################################
  ArtifactsBucket:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${S3BucketName}
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

################################################################################################
# S3 Bucket Policy
################################################################################################
  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${ArtifactsBucket}
              - !Sub arn:aws:s3:::${ArtifactsBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root

################################################################################################
# Outputs
################################################################################################
Outputs:
################################################################################################
  ArtifactsBucketName:
    Description: 'The Artifacts Bucket'
    Value: !Ref ArtifactsBucket
    Export:
      Name: ArtifactsBucketName
    
